### ISSUE TITLE
Some routers return empty space prefixed in XML response text (BUG!)

### ISSUE THREAD

**Issue by zezba9000** [lontivero/Open.NAT#106]
In the file "SoapClient.cs" this line of code "var responseXml = GetXmlDocument(responseBody);" should be changed to "var responseXml = GetXmlDocument(responseBody.Trim());".

In short you need to add ".Trim()" to the "responseBody" string as some older routers return empty text prefixing the body. This ends up causing XML exceptions for otherwise successful responses.

I've fixed this in my fork: https://github.com/zezba9000/Open.NAT/commit/e71a3f815e3f5a6f8df5f85551c71572e4da8493#diff-c2e74342cdb0f32b9ebd1f0af27735e95cf33a39ade1a554ce80622ccead63aeR126

My fork has more changes I didn't want to do a pull-request with though. So posting the fix here.

**Comment by lontivero** [comment]
Fixed: https://github.com/lontivero/Open.NAT/commit/dc8101129a395319cba8e55cf52f576aeee0c74b

**Comment by zezba9000** [comment]
Awesome!
