### ISSUE TITLE
Avoid the generic and unused namespace Open.

### ISSUE THREAD

**Issue by Mailaender** [lontivero/Open.NAT#21]
It is a bit annoying to work with IDEs when you type `using Op<TAB>` it gives you `using Open.` which is not helpful. You always want `using Open.Nat`. When using it in @OpenRA it is also conflicting a lot. I suggest to go with `OpenNat` instead.

**Comment by lontivero** [comment]
I understand what you say. The point is that change will break all the clients and we don't know what projects are using open.nat. Another fact is that I use 'Open' for all my projects (for those that I really care) so, @OpenRA will use alway Open.Nat but other projects could potencially use Open.Nat, Open.WinKeyboardHook or Open.HttpProxy.

I appreciate his kind of recomendations from those, like you, that have real requirements for real world projects but I cannot change the namespace even when it could be useful for some projects.

**Comment by Mailaender** [comment]
I agree, it is probably too late already.
