### ISSUE TITLE
GetSpecificMappingAsync under DD-WRT it returns errorcode 402

### ISSUE THREAD

**Issue by lontivero** [lontivero/Open.NAT#24]
When calling GetSpecificMappingAsync under DD-WRT it returns errorcode 402. Please see soap request & response attached.

![capture](https://cloud.githubusercontent.com/assets/11742960/7260627/70c42318-e839-11e4-8816-4fa8de4879d4.png)

Reported by user @at1993 on issue #22

**Comment by at1993** [comment]
When calling GetSpecificMappingAsync under LINKSYS WRT1900AC AC1900 it returns errocode 501
errorDescription: PAL_UPNP_SOAP_E_ACTION_FAILED
NOTE: this occurs when specific entry does not exist.

**Comment by lontivero** [comment]
I will take a look at this this week. Thank you @at1993
