### ISSUE TITLE
Action not authorized From GetAllMappingsAsync

### ISSUE THREAD

**Issue by at1993** [lontivero/Open.NAT#30]
The GetAllMappingsAsync failed in a Sagemcom Fast 5250 router.
The error returned as below with wireshark capature attached.

Open.NAT - Information > GetAllMappingsAsync - Getting all mappings
Open.NAT - Warning > Server failed with error: 606 - Action not authorized

Any ideas? 

![untitled](https://cloud.githubusercontent.com/assets/11742960/9291440/b9d6e4f0-438d-11e5-8624-e81b462bc51c.png)

**Comment by at1993** [comment]
Looks like a broken implementation of Upnp by Sagemcom (Model Fast 5250).

**Comment by lontivero** [comment]
@at1993 the request seems to be correct. I have to do some research about the error in Sagemcom. I hope to have a fix in a week or two.

**Comment by lontivero** [comment]
@at1993 provably the discovered UPnp device **is not** your Sagemcom router but a media server in your local network.

I need more information. Please, run the **Open.Nat.ConsoleTest** console application and share the **network.log** file here.

**Comment by at1993** [comment]
Thank you for looking into this. Below is the log file. Notice that it responded to the GetExternalIP query.

Open.NAT Information: 0 : Start Discovery
Open.NAT Information: 0 : Searching for: UpnpSearcher
Open.NAT Information: 0 : UPnP Response: Router advertised a &aposurn:schemas-upnp-org:service:WANPPPConnection:1&apos service!!!
Open.NAT Information: 0 : Found device at: http://192.168.2.1:49155/37676c4e/gatedesc.xml
Open.NAT Information: 0 : 192.168.2.1:49155: Fetching service list
Open.NAT Information: 0 : Found device at: http://192.168.2.1:49155/37676c4e/gatedesc.xml
System.Net Verbose: 0 : [9088] WebRequest::Create(http://192.168.2.1:49155/37676c4e/gatedesc.xml)
System.Net Verbose: 0 : [9088] HttpWebRequest#33156464::HttpWebRequest(http://192.168.2.1:49155/37676c4e/gatedesc.xml#-478230164)
System.Net Information: 0 : [9088] HttpWebRequest#33156464 - Request: GET /37676c4e/gatedesc.xml HTTP/1.1

System.Net Information: 0 : [9088] ConnectStream#7588182 - Sending headers
{
ACCEPT-LANGUAGE: en
Host: 192.168.2.1:49155
Connection: Keep-Alive
}.
System.Net Information: 0 : [9088] Connection#32977404 - Received status line: Version=1.1, StatusCode=200, StatusDescription=OK.
System.Net Information: 0 : [9088] Connection#32977404 - Received headers
{
X-User-Agent: redsonic
CONNECTION: close
Content-Length: 3276
Content-Type: text/xml
Date: Tue, 18 Aug 2015 02:16:41 GMT
Last-Modified: Tue, 18 Aug 2015 02:16:41 GMT
Server: Linux/2.6.28.8, UPnP/1.0, Portable SDK for UPnP devices/1.6.18
}.
System.Net Verbose: 0 : [9088] &lt;&lt;&lt;?xml version=&quot;1.0&quot;?&gt;
&lt;root xmlns=&quot;urn:schemas-upnp-org:device-1-0&quot;&gt;
  &lt;specVersion&gt;
    &lt;major&gt;1&lt;/major&gt;
    &lt;minor&gt;0&lt;/minor&gt;
  &lt;/specVersion&gt;
  &lt;device&gt;
    &lt;deviceType&gt;urn:schemas-upnp-org:device:InternetGatewayDevice:2&lt;/deviceType&gt;
    &lt;friendlyName&gt;Home Hub 2000 Internet Gateway Device&lt;/friendlyName&gt;
    &lt;manufacturer&gt;Sagemcom&lt;/manufacturer&gt;
    &lt;manufacturerURL&gt;http://www.sagemcom.com&lt;/manufacturerURL&gt;
    &lt;modelDescription&gt;Home Hub 2000 Internet Gateway Device&lt;/modelDescription&gt;
    &lt;modelName&gt;Sagemcom IDG WAN&lt;/modelName&gt;
    &lt;modelNumber&gt;&lt;/modelNumber&gt;
    &lt;presentationURL&gt;http://192.168.2.1:80&lt;/presentationURL&gt;
    &lt;UDN&gt;uuid:75802409-bccb-40e7-8e6c-fa095ecce13e&lt;/UDN&gt;
    &lt;UPC&gt;&lt;/UPC&gt;
    &lt;iconList&gt;
      &lt;icon&gt;
        &lt;mimetype&gt;image/png&lt;/mimetype&gt;
        &lt;width&gt;16&lt;/width&gt;
        &lt;height&gt;16&lt;/height&gt;
        &lt;depth&gt;8&lt;/depth&gt;
        &lt;url&gt;/ligd.png&lt;/url&gt;
      &lt;/icon&gt;
    &lt;/iconList&gt;
    &lt;deviceList&gt;
      &lt;device&gt;
        &lt;deviceType&gt;urn:schemas-upnp-org:device:WANDevice:2&lt;/deviceType&gt;
        &lt;frie&gt;&gt;
System.Net Verbose: 0 : [9088] &lt;&lt;ndlyName&gt;External WAN Device&lt;/friendlyName&gt;
        &lt;manufacturer&gt;Sagemcom&lt;/manufacturer&gt;
        &lt;manufacturerURL&gt;http://www.sagemcom.com&lt;/manufacturerURL&gt;
        &lt;modelDescription&gt;&lt;/modelDescription&gt;
        &lt;modelName&gt;Sagemcom IGD WAN&lt;/modelName&gt;
        &lt;modelNumber&gt;&lt;/modelNumber&gt;
        &lt;modelURL&gt;&lt;/modelURL&gt;
        &lt;serialNumber&gt;&lt;/serialNumber&gt;
        &lt;presentationURL&gt;http://192.168.2.1:80&lt;/presentationURL&gt;
        &lt;UDN&gt;uuid:75802409-bccb-40e7-8e6c-fa095ecce13f&lt;/UDN&gt;
        &lt;UPC&gt;&lt;/UPC&gt;
        &lt;serviceList&gt;
          &lt;service&gt;
            &lt;serviceType&gt;urn:schemas-upnp-org:service:WANCommonInterfaceConfig:1&lt;/serviceType&gt;
            &lt;serviceId&gt;urn:upnp-org:serviceId:WANCommonIFC1&lt;/serviceId&gt;
            &lt;controlURL&gt;/upnp/control/WANCommonIFC1&lt;/controlURL&gt;
            &lt;eventSubURL&gt;/upnp/control/WANCommonIFC1&lt;/eventSubURL&gt;
            &lt;SCPDURL&gt;/37676c4e/wancomicfgSCPD.xml&lt;/SCPDURL&gt;
          &lt;/service&gt;
        &lt;/serviceList&gt;
        &lt;deviceList&gt;
          &lt;device&gt;
            &lt;deviceType&gt;urn:schemas-up&gt;&gt;
System.Net Verbose: 0 : [9088] &lt;&lt;np-org:device:WANConnectionDevice:2&lt;/deviceType&gt;
            &lt;friendlyName&gt;Home Hub 2000 WAN Connection Device&lt;/friendlyName&gt;
            &lt;manufacturer&gt;Sagemcom&lt;/manufacturer&gt;
            &lt;manufacturerURL&gt;http://www.sagemcom.com&lt;/manufacturerURL&gt;
            &lt;modelDescription&gt;WANConnectionDevice on Linux IGD&lt;/modelDescription&gt;
            &lt;modelName&gt;Sagemcom IGD WANConnection&lt;/modelName&gt;
            &lt;modelNumber&gt;&lt;/modelNumber&gt;
            &lt;modelURL&gt;&lt;/modelURL&gt;
            &lt;serialNumber&gt;&lt;/serialNumber&gt;
            &lt;presentationURL&gt;http://192.168.2.1:80&lt;/presentationURL&gt;
            &lt;UDN&gt;uuid:75802409-bccb-40e7-8e6c-fa095ecce140&lt;/UDN&gt;
            &lt;UPC&gt;&lt;/UPC&gt;
            &lt;serviceList&gt;
              &lt;service&gt;
                &lt;serviceType&gt;urn:schemas-upnp-org:service:WANPPPConnection:1&lt;/serviceType&gt;
                &lt;serviceId&gt;urn:upnp-org:serviceId:WANPPPConn0&lt;/serviceId&gt;
                &lt;controlURL&gt;/upnp/control/WANPPPConn0&lt;/controlURL&gt;
                &lt;eventSubURL&gt;/upnp/control/WANPPPConn0&lt;/eventSubURL&gt;
        &gt;&gt;
System.Net Verbose: 0 : [9088] &lt;&lt;        &lt;SCPDURL&gt;/37676c4e/wanpppconnSCPD.xml&lt;/SCPDURL&gt;
              &lt;/service&gt;
            &lt;/serviceList&gt;
          &lt;/device&gt;
        &lt;/deviceList&gt;
      &lt;/device&gt;
    &lt;/deviceList&gt;
  &lt;/device&gt;
&lt;/root&gt;
&gt;&gt;
Open.NAT Information: 0 : 192.168.2.1:49155: Parsed services list
Open.NAT Information: 0 : 192.168.2.1:49155: Found service: urn:schemas-upnp-org:service:WANPPPConnection:1
Open.NAT Information: 0 : 192.168.2.1:49155: Found upnp service at: /upnp/control/WANPPPConn0
Open.NAT Information: 0 : 192.168.2.1:49155: Handshake Complete
Open.NAT Information: 0 : Stop Discovery
Open.NAT Information: 0 : GetExternalIPAsync - Getting external IP address
System.Net Verbose: 0 : [9088] WebRequest::Create(http://192.168.2.1:49155/upnp/control/WANPPPConn0)
System.Net Verbose: 0 : [9088] HttpWebRequest#50510248::HttpWebRequest(http://192.168.2.1:49155/upnp/control/WANPPPConn0#-1457156879)
System.Net Information: 0 : [3656] HttpWebRequest#50510248 - Request: POST /upnp/control/WANPPPConn0 HTTP/1.1

System.Net Information: 0 : [3656] ConnectStream#15510466 - Sending headers
{
Content-Type: text/xml; charset=&quot;utf-8&quot;
SOAPACTION: &quot;urn:schemas-upnp-org:service:WANPPPConnection:1#GetExternalIPAddress&quot;
Host: 192.168.2.1:49155
Content-Length: 303
Expect: 100-continue
Connection: Close
}.
System.Net Verbose: 0 : [9088] &lt;&lt;&lt;s:Envelope 
   xmlns:s=&quot;http://schemas.xmlsoap.org/soap/envelope/&quot; 
   s:encodingStyle=&quot;http://schemas.xmlsoap.org/soap/encoding/&quot;&gt;
   &lt;s:Body&gt;
      &lt;u:GetExternalIPAddress xmlns:u=&quot;urn:schemas-upnp-org:service:WANPPPConnection:1&quot;&gt;
      &lt;/u:GetExternalIPAddress&gt;
   &lt;/s:Body&gt;
&lt;/s:Envelope&gt;

&gt;&gt;
System.Net Information: 0 : [3656] Connection#7995840 - Received status line: Version=1.1, StatusCode=200, StatusDescription=OK.
System.Net Information: 0 : [3656] Connection#7995840 - Received headers
{
EXT: 
X-User-Agent: redsonic
Content-Length: 343
Content-Type: text/xml; charset=&quot;utf-8&quot;
Date: Tue, 18 Aug 2015 02:16:41 GMT
Server: Linux/2.6.28.8, UPnP/1.0, Portable SDK for UPnP devices/1.6.18
}.
System.Net Verbose: 0 : [9088] &lt;&lt;&lt;s:Envelope xmlns:s=&quot;http://schemas.xmlsoap.org/soap/envelope/&quot; s:encodingStyle=&quot;http://schemas.xmlsoap.org/soap/encoding/&quot;&gt;&lt;s:Body&gt;
&lt;u:GetExternalIPAddressResponse xmlns:u=&quot;urn:schemas-upnp-org:service:WANPPPConnection:1&quot;&gt;
&lt;NewExternalIPAddress&gt;##.##.###.###&lt;/NewExternalIPAddress&gt;
&lt;/u:GetExternalIPAddressResponse&gt;
&lt;/s:Body&gt; &lt;/s:Envelope&gt;&gt;&gt;
Open.NAT Information: 0 : GetAllMappingsAsync - Getting all mappings
System.Net Verbose: 0 : [9088] WebRequest::Create(http://192.168.2.1:49155/upnp/control/WANPPPConn0)
System.Net Verbose: 0 : [9088] HttpWebRequest#63630067::HttpWebRequest(http://192.168.2.1:49155/upnp/control/WANPPPConn0#-1457156879)
System.Net Information: 0 : [8328] HttpWebRequest#63630067 - Request: POST /upnp/control/WANPPPConn0 HTTP/1.1

System.Net Information: 0 : [8328] ConnectStream#34250480 - Sending headers
{
Content-Type: text/xml; charset=&quot;utf-8&quot;
SOAPACTION: &quot;urn:schemas-upnp-org:service:WANPPPConnection:1#GetGenericPortMappingEntry&quot;
Host: 192.168.2.1:49155
Content-Length: 370
Expect: 100-continue
Connection: Close
}.
System.Net Verbose: 0 : [2344] &lt;&lt;&lt;s:Envelope 
   xmlns:s=&quot;http://schemas.xmlsoap.org/soap/envelope/&quot; 
   s:encodingStyle=&quot;http://schemas.xmlsoap.org/soap/encoding/&quot;&gt;
   &lt;s:Body&gt;
      &lt;u:GetGenericPortMappingEntry xmlns:u=&quot;urn:schemas-upnp-org:service:WANPPPConnection:1&quot;&gt;
         &lt;NewPortMappingIndex&gt;0&lt;/NewPortMappingIndex&gt;
      &lt;/u:GetGenericPortMappingEntry&gt;
   &lt;/s:Body&gt;
&lt;/s:Envelope&gt;

&gt;&gt;
System.Net Information: 0 : [8328] Connection#4878312 - Received status line: Version=1.1, StatusCode=500, StatusDescription=Internal Server Error.
System.Net Information: 0 : [8328] Connection#4878312 - Received headers
{
EXT: 
X-User-Agent: redsonic
Content-Length: 419
Content-Type: text/xml; charset=&quot;utf-8&quot;
Date: Tue, 18 Aug 2015 02:16:41 GMT
Server: Linux/2.6.28.8, UPnP/1.0, Portable SDK for UPnP devices/1.6.18
}.
System.Net Verbose: 0 : [8328] &lt;&lt;&lt;s:Envelope xmlns:s=&quot;http://schemas.xmlsoap.org/soap/envelope/&quot; s:encodingStyle=&quot;http://schemas.xmlsoap.org/soap/encoding/&quot;&gt;
&lt;s:Body&gt;
&lt;s:Fault&gt;
&lt;faultcode&gt;s:Client&lt;/faultcode&gt;
&lt;faultstring&gt;UPnPError&lt;/faultstring&gt;
&lt;detail&gt;
&lt;UPnPError xmlns=&quot;urn:schemas-upnp-org:control-1-0&quot;&gt;
&lt;errorCode&gt;606&lt;/errorCode&gt;
&lt;errorDescription&gt;Action not authorized&lt;/errorDescription&gt;
&lt;/UPnPError&gt;
&lt;/detail&gt;
&lt;/s:Fault&gt;
&lt;/s:Body&gt;
&lt;/s:Envelope&gt;
&gt;&gt;
System.Net Error: 0 : [8328] Exception in HttpWebRequest#63630067::EndGetResponse - The remote server returned an error: (500) Internal Server Error..
Open.NAT Warning: 0 : Server failed with error: 606 - Action not authorized

**Comment by lontivero** [comment]
After reviewing this log carefully, I cannot find any error in Open.NAT. The request is well-formed and also the parameters. The endpoint looks okay and, in fact, it returns the external IP correctly.

I think the router could have some configuration to prevent (unathorize) some actions. In that case, Open.NAT cannot help you.

If you find something else I will review it again but the problem is clearly on the router side.

**Comment by at1993** [comment]
@lontivero I appreciate your effort. I did a few tests against this router tonight and found some interesting findings. 
1. It will response to GetSpecificPortMappingEntry if the mapping is owned by you otherwise, an "action not authorized" is returned.
2. The same goes for DeletePortMapping.
3. I have some IoT that needs to have its port open via the AddPortMapping (my app will opens it on its behalf).  This step will fail because the InternalClientIP entry must be equaled to the IP where requested traffic is coming from.

Do you know if these findings are within the uPnP specs????

**Comment by lontivero** [comment]
Sorry for the delay in my response. Look, old Open.NAT versions didn't allow you to use other IP addresses for InternalClientIP other that the machine performing the request. I've changed that to allow other use cases, I tested and everything was alright,

The UPnP specs don't say anything about that (even when it is a common sense validation).

[Here](http://www.upnp-hacks.org/igd.html), you can read the following:

>The specifications for the IGD profile allow any control point ot use AddPortMapping to forward ports to other machines on the LAN. While it can be convenient, it is really easy this way to open file servers, printers and other machines/devices to the outside world.

> A fairly solution would be to not allow a control point to ask for port forwards for another IP address except its own. This will make the device not UPnP IGD compatible (strictly speaking), but I am fairly sure that every application/device that depends on port forwards will not break, since these applications/devices only ask for port forwards to themselves.

In the log I can see the router is using WANPPPConnection version 1 so, you can verify what I say just reading the specs:

[http://upnp.org/specs/gw/UPnP-gw-WANPPPConnection-v1-Service.pdf](http://upnp.org/specs/gw/UPnP-gw-WANPPPConnection-v1-Service.pdf)

Moreover, errors 600-699 (unathorized error, for example) were defined for version 2.
