### ISSUE TITLE
Open.NAT - Warning > Server failed with error: 402 - Invalid Argument

### ISSUE THREAD

**Issue by ecklerpa** [lontivero/Open.NAT#38]
Hey there, just wanted to report what I got when I ran your test utility incase others come across the same issue:
*_Open.NAT - Information > Start Discovery
Open.NAT - Information > Searching for: UpnpSearcher
Open.NAT - Information > UPnP Response: Router advertised a 'urn:schemas-upnp-org:service:WANIPConnection:1' service!!!
Open.NAT - Information > Found device at: http://192.168.1.1:1780/InternetGatewayDevice.xml
Open.NAT - Information > 192.168.1.1:1780: Fetching service list
Open.NAT - Information > Found device at: http://192.168.1.1:1780/InternetGatewayDevice.xml
Open.NAT - Information > 192.168.1.1:1780: Parsed services list
Open.NAT - Information > 192.168.1.1:1780: Found service: urn:schemas-upnp-org:service:WANIPConnection:1
Open.NAT - Information > 192.168.1.1:1780: Found upnp service at: /control?WANIPConnection
Open.NAT - Information > 192.168.1.1:1780: Handshake Complete
Open.NAT - Information > Stop Discovery
Open.NAT - Information > GetExternalIPAsync - Getting external IP address
Open.NAT - Information > CreatePortMapAsync - Creating port mapping Tcp 1703 --> 192.168.1.100:1603 (Open.Nat (Manual lifetime))
Open.NAT - Warning > Server failed with error: 402 - Invalid Argument
EXCEPTION: Error 402: Invalid Argument
*_

**Comment by lontivero** [comment]
@ecklerpa thanks for reporting this. Could you please switch the tracing feature to verbose mode and send me the output again?

use:

     NatDiscoverer.TraceSource.Switch.Level = SourceLevels.Verbose;

**Comment by ecklerpa** [comment]
Sure thing... it throws the exception as soon as it gets to the 'await device.CreatePortMapAsync(new Mapping(....)' function.
Open.NAT - Information > Stop Discovery
Open.NAT - Information > GetExternalIPAsync - Getting external IP address
Open.NAT - Verbose > SOAPACTION: **GetExternalIPAddress** url:http://192.168.1.1:1780/control?WANIPConnection
Open.NAT - Information > CreatePortMapAsync - Creating port mapping Tcp 1703 --> 192.168.1.100:1603 (Open.Nat (Manual lifetime))
Open.NAT - Verbose > SOAPACTION: **AddPortMapping** url:http://192.168.1.1:1780/control?WANIPConnection
Open.NAT - Verbose > WebException status: ProtocolError
Open.NAT - Warning > Server failed with error: 402 - Invalid Argument

**Comment by ecklerpa** [comment]
Here is some of the Output from my Visual Studio if that helps:

System.Net Information: 0 : [4400] ConnectStream#49538252 - Sending headers
{
Content-Type: text/xml; charset="utf-8"
SOAPACTION: "urn:schemas-upnp-org:service:WANIPConnection:1#AddPortMapping"
Host: 192.168.1.1:1780
Content-Length: 715
Expect: 100-continue
Connection: Close
}.
System.Net Verbose: 0 : [15756] HttpWebRequest#14421545::EndGetRequestStream()
System.Net Verbose: 0 : [15756] Exiting HttpWebRequest#14421545::EndGetRequestStream() 	-> ConnectStream#49538252
System.Net Verbose: 0 : [15756] ConnectStream#49538252::BeginWrite()
System.Net Verbose: 0 : [15756] Data from ConnectStream#49538252::BeginWrite
System.Net Verbose: 0 : [15756] <<<s:Envelope 
   xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" 
   s:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/">
   <s:Body>
      <u:AddPortMapping xmlns:u="urn:schemas-upnp-org:service:WANIPConnection:1">
         <NewRemoteHost></NewRemoteHost>
         <NewExternalPort>1703</NewExternalPort>
         <NewProtocol>TCP</NewProtocol>
         <NewInternalPort>1603</NewInternalPort>
         <NewInternalClient>192.168.1.100</NewInternalClient>
         <NewEnabled>1</NewEnabled>
         <NewPortMappingDescription>Open.Nat (Manual lifetime)</NewPortMappingDescription>
         <NewLeaseDuration>20</NewLeaseDuration>
      </u:AddPortMapping>
   </s:Body>
</s:Envelope>

>>
System.Net Verbose: 0 : [15756] Exiting ConnectStream#49538252::BeginWrite() 	-> NestedSingleAsyncResult#39053774
System.Net Verbose: 0 : [15756] ConnectStream#49538252::EndWrite()
System.Net Verbose: 0 : [15756] Exiting ConnectStream#49538252::EndWrite() 
System.Net Verbose: 0 : [15756] ConnectStream#49538252::Close()
System.Net Verbose: 0 : [15756] Exiting ConnectStream#49538252::Close() 
System.Net Verbose: 0 : [17088] HttpWebRequest#14421545::BeginGetResponse()
System.Net Information: 0 : [4400] Connection#39774547 - Received status line: Version=1.1, StatusCode=500, StatusDescription=Internal Server Error.
System.Net Information: 0 : [4400] Connection#39774547 - Received headers
{
EXT: 
Connection: close
Content-Length: 400
Content-Type: text/xml; charset="utf-8"
Date: Fri, 15 Apr 2016 20:29:38 GMT
Server: POSIX, UPnP/1.0 linux/5.10.56.51
}.
System.Net Information: 0 : [4400] ConnectStream#62696216::ConnectStream(Buffered 400 bytes.)
System.Net Information: 0 : [4400] Associating HttpWebRequest#14421545 with ConnectStream#62696216
System.Net Information: 0 : [4400] Associating HttpWebRequest#14421545 with HttpWebResponse#31071611
System.Net Verbose: 0 : [4400] ConnectStream#62696216::Read()
System.Net Verbose: 0 : [17088] Exiting HttpWebRequest#14421545::BeginGetResponse() 	-> ContextAwareResult#30180123
System.Net Verbose: 0 : [4400] Data from ConnectStream#62696216::Read
System.Net Verbose: 0 : [4400] <<<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" s:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"><s:Body><s:Fault><faultcode>s:Client</faultcode><faultstring>UPnPError</faultstring><detail><UPnPError xmlns="urn:schemas-upnp-org:control-1-0"><errorCode>402</errorCode><errorDescription>Invalid Argument</errorDescription></UPnPError></detail></s:Fault></s:Body></s:Envelope>>>
System.Net Verbose: 0 : [4400] Exiting ConnectStream#62696216::Read() 	-> Int32#400
System.Net Verbose: 0 : [4400] ConnectStream#62696216::Read()
System.Net Verbose: 0 : [4400] Exiting ConnectStream#62696216::Read() 	-> Int32#0
System.Net Verbose: 0 : [4400] HttpWebRequest#14421545::EndGetResponse()
System.Net Error: 0 : [4400] Exception in HttpWebRequest#14421545::EndGetResponse - The remote server returned an error: (500) Internal Server Error..
A first chance exception of type 'System.Net.WebException' occurred in mscorlib.dll
Open.NAT Verbose: 0 : WebException status: ProtocolError
System.Net Verbose: 0 : [4400] HttpWebResponse#31071611::GetResponseStream()
System.Net Information: 0 : [4400] ContentLength=400
System.Net Verbose: 0 : [4400] Exiting HttpWebResponse#31071611::GetResponseStream() 	-> SyncMemoryStream#63566392
Open.NAT Warning: 0 : Server failed with error: 402 - Invalid Argument
A first chance exception of type 'Open.Nat.MappingException' occurred in Open.Nat.dll
System.Net Verbose: 0 : [4400] HttpWebResponse#31071611::Close()
System.Net Verbose: 0 : [4400] Exiting HttpWebResponse#31071611::Close() 
A first chance exception of type 'Open.Nat.MappingException' occurred in mscorlib.dll

**Comment by ecklerpa** [comment]
So I updated my routers firmware to resolve this issue.
I have a linksys E3000.
Updated the Firmware to Version: 1.0.06
