### ISSUE TITLE
Using Open.NAT

### ISSUE THREAD

**Issue by ibpet11** [lontivero/Open.NAT#40]
Hello Sir,

I had to signup in order to get to you, glad for that anyway.
Firstly I have a remote desktop application like teamviewer, it works on same network but going over the internet I have serious issues. I downloaded the Open.NAT and add it up to my project in vb.net as dependency. I have serious issues with these two statement in vb.net. Please guide me on this.

> var device = await discoverer.DiscoverDeviceAsync();
> var ip = await device.GetExternalIPAsync();

I also believe with your Open.NAT solution I should be able to achieve my goal of port forwarding a particular port.
If you have better idea or solution kindly assist me.

Thank you.

**Comment by lontivero** [comment]
@ibpet11 I don't really understand what exactly your question is. I think you don't know how to use await/async in vb.net, if that is the point you could take a look at [this](https://msdn.microsoft.com/en-us/library/hh156570.aspx)

Or, probably you are using a .NET version < 3.5. Could that be the case? What .net version are you using?

**Comment by ibpet11** [comment]
Mr Lucas,
Thank you for your response.
Honestly, I do not know how to use await/async in vb.net so I translated the c# to vb.net yet still error at that point. I used 4.5 .Net in my application.

Perhaps let me explain myself and target very well. I have a remote desktop application like teamviewer, it works on local network, but cant work over the internet so after reading much on the internet I found your solution which I believe should help open port on system A so that system B from another location can connect over the internet. so irrespective of the router and firewall setting I want every user of the application use it without bothering what happen. you know we use teamviewer without need to change firewall or router setting.

I hope Open.NAT will be able to assist in getting my dream come through.

**Comment by lontivero** [comment]
@ibpet11 sorry for the delay in my response, i was unavailable. 

Open.NAT was developed exactly for the use case that you described. 

Using ILSpy i translated the ConsoleTest project from c# to VB.NET and this is how it looks like:

```vbnet
Imports System
Imports System.Net
Imports System.Net.Sockets
Imports System.Text
Imports System.Threading
Imports System.Threading.Tasks

Namespace Open.Nat.ConsoleTest
	Friend Class NatTest
		Public Shared Sub Main(args As String())
			NatTest.Test().Wait()
			Console.WriteLine("")
			Console.WriteLine("Socket listening on port 1602. Remember, it is mapped to external port 1702!!!")
			Console.WriteLine("Test it with http://www.canyouseeme.org/ online tool")
			Dim endPoint As IPEndPoint = New IPEndPoint(IPAddress.Any, 1602)
			Dim socket As Socket = New Socket(endPoint.AddressFamily, SocketType.Stream, ProtocolType.Tcp)
			socket.SetIPProtectionLevel(IPProtectionLevel.Unrestricted)
			socket.Bind(endPoint)
			socket.Listen(4)
			Console.WriteLine("Press any key to exit...")
			Console.ReadKey()
			socket.Close()
		End Sub

		Private Shared Async Function Test() As Task
			Dim natDiscoverer As NatDiscoverer = New NatDiscoverer()
			Dim cancellationTokenSource As CancellationTokenSource = New CancellationTokenSource(5000)
			Dim upnpNatDevice As UpnpNatDevice = Await natDiscoverer.DiscoverDeviceAsync(cancellationTokenSource)
			Dim stringBuilder As StringBuilder = New StringBuilder()
			Dim iPAddress As IPAddress = Await upnpNatDevice.GetExternalIPAsync()
			stringBuilder.AppendFormat(vbLf & "Your IP: {0}", iPAddress)
			Await upnpNatDevice.CreatePortMapAsync(New Mapping(Protocol.Tcp, 1600, 1700, "Open.Nat (temporary)"))
			Await upnpNatDevice.CreatePortMapAsync(New Mapping(Protocol.Tcp, 1601, 1701, "Open.Nat (Session lifetime)"))
			Await upnpNatDevice.CreatePortMapAsync(New Mapping(Protocol.Tcp, 1602, 1702, 0, "Open.Nat (Permanent lifetime)"))
			Await upnpNatDevice.CreatePortMapAsync(New Mapping(Protocol.Tcp, 1603, 1703, 20, "Open.Nat (Manual lifetime)"))
			stringBuilder.AppendFormat(vbLf & "Added mapping: {0}:1700 -> 127.0.0.1:1600" & vbLf, iPAddress)
			stringBuilder.AppendFormat(vbLf & "+------+-------------------------------+--------------------------------+------------------------------------+-------------------------+", New Object(-1) {})
			stringBuilder.AppendFormat(vbLf & "| PROT | PUBLIC (Reacheable)" & vbTab & vbTab & "   | PRIVATE (Your computer)" & vbTab & vbTab & "| Descriptopn" & vbTab & vbTab & vbTab & vbTab & vbTab & vbTab & "|" & vbTab & vbTab & vbTab & vbTab & vbTab & vbTab & " |", New Object(-1) {})
			stringBuilder.AppendFormat(vbLf & "+------+----------------------+--------+-----------------------+--------+------------------------------------+-------------------------+", New Object(-1) {})
			stringBuilder.AppendFormat(vbLf & "|" & vbTab & "  | IP Address" & vbTab & vbTab & "   | Port   | IP Address" & vbTab & vbTab & vbTab & "| Port   |" & vbTab & vbTab & vbTab & vbTab & vbTab & vbTab & vbTab & vbTab & vbTab & "| Expires" & vbTab & vbTab & vbTab & vbTab & " |", New Object(-1) {})
			stringBuilder.AppendFormat(vbLf & "+------+----------------------+--------+-----------------------+--------+------------------------------------+-------------------------+", New Object(-1) {})
			For Each mapping As Mapping In Await upnpNatDevice.GetAllMappingsAsync()
				stringBuilder.AppendFormat(vbLf & "|  {5} | {0,-20} | {1,6} | {2,-21} | {3,6} | {4,-35}|{6,25}|", New Object() { iPAddress, mapping.PublicPort, mapping.PrivateIP, mapping.PrivatePort, mapping.Description, If((mapping.Protocol = Protocol.Tcp), "TCP", "UDP"), mapping.Expiration.ToLocalTime() })
			Next
			stringBuilder.AppendFormat(vbLf & "+------+----------------------+--------+-----------------------+--------+------------------------------------+-------------------------+", New Object(-1) {})
			stringBuilder.AppendFormat(vbLf & "[Removing TCP mapping] {0}:1700 -> 127.0.0.1:1600", iPAddress)
			Await upnpNatDevice.DeletePortMapAsync(New Mapping(Protocol.Tcp, 1600, 1700))
			stringBuilder.AppendFormat(vbLf & "[Done]", New Object(-1) {})
			Console.WriteLine(stringBuilder.ToString())
		End Function
	End Class
End Namespace
```

I hope this is what you need.

**Comment by ibpet11** [comment]
@lontivero 

Thank you for taking time to respond to me wonderfully.
I observe another issue and trying to debug I discovered within the Test() function above I couldnt move beyond this line "            Dim upnpNatDevice As UpnpNatDevice = Await natDiscoverer.DiscoverDeviceAsync(cancellationTokenSource)". I waited for more than half an hour to see result but all to no avail. Could it be because I am using a modem as my internet medium?
I couldn't find any log in the bin folder that I could have share with you.

Anyway out?

Thank you.

**Comment by lontivero** [comment]
@ibpet11 i've cloned the full repo locally again and i've run the ConsoleTest project and it does gerenates a network.log file where the executable is located. It also prints a good amount of info in the console. I need the log file, without it there is nothing i can do.
