### ISSUE TITLE
UpnpNatDevice.GetSpecificMappingAsync returns wrong protocol

### ISSUE THREAD

**Issue by bartwe** [lontivero/Open.NAT#45]
UpnpNatDevice.GetSpecificMappingAsync (without NET35 defined)

Can return mappings with a different protocol than requested.
This is likely due to router firmware bugs or it binding a portnumber and ignoring the protocol.
(Replicated with a Fritz!box 7490)

Given that the protocol is an argument to the function the result can take this value directly and log a trace noting the conflict.

Suggested code:

		public override async Task<Mapping> GetSpecificMappingAsync (Protocol protocol, int publicPort)
		{
			Guard.IsTrue(protocol == Protocol.Tcp || protocol == Protocol.Udp, "protocol");
			Guard.IsInRange(publicPort, 0, ushort.MaxValue, "port");

			NatDiscoverer.TraceSource.LogInfo("GetSpecificMappingAsync - Getting mapping for protocol: {0} port: {1}", Enum.GetName(typeof(Protocol), protocol), publicPort);

			try
			{
				var message = new GetSpecificPortMappingEntryRequestMessage(protocol, publicPort);
				var responseData = await _soapClient
					.InvokeAsync("GetSpecificPortMappingEntry", message.ToXml())
					.TimeoutAfter(TimeSpan.FromSeconds(4));

				var messageResponse = new GetPortMappingEntryResponseMessage(responseData, DeviceInfo.ServiceType, false);

                if (messageResponse.Protocol != protocol)
                    NatDiscoverer.TraceSource.LogWarn("Router responded to a protocol {0} query with a protocol {1} answer, work around applied.", protocol, messageResponse.Protocol);

				return new Mapping(protocol
					, IPAddress.Parse(messageResponse.InternalClient)
					, messageResponse.InternalPort
					, publicPort // messageResponse.ExternalPort is short.MaxValue
					, messageResponse.LeaseDuration
					, messageResponse.PortMappingDescription);
			}
			catch (MappingException e)
			{
				// there are no more mappings
				if (e.ErrorCode == UpnpConstants.SpecifiedArrayIndexInvalid
				 || e.ErrorCode == UpnpConstants.NoSuchEntryInArray
					// DD-WRT Linux base router (and others probably) fails with 402-InvalidArgument when index is out of range
				 || e.ErrorCode == UpnpConstants.InvalidArguments
					// LINKSYS WRT1900AC AC1900 it returns errocode 501-PAL_UPNP_SOAP_E_ACTION_FAILED
				 || e.ErrorCode == UpnpConstants.ActionFailed)
				{
					NatDiscoverer.TraceSource.LogWarn("Router failed with {0}-{1}. No more mappings is assumed.", e.ErrorCode, e.ErrorText);
					return null;
				}
				throw;
			}
		}

**Comment by lontivero** [comment]
fixed on 0da6a049cce36d2c9cd69f4c9e86e7b24ab12d2f- Thanks, @bartwe
