### ISSUE TITLE
Evaluate the use of useUnsafeHeaderParsing for buggy devices

### ISSUE THREAD

**Issue by lontivero** [lontivero/Open.NAT#50]
>Forum:	article "Open.NAT - A NAT Traversal library for .NET and Mono"
>Subject:	3 bugs   (View)
>Sender:	gunnarD
>Date:	Thursday, August 11, 2016 9:53am

Need to add this to app.config, else I get exception "The server committed a protocol violation. Section=ResponseStatusLine"
```
<system.net>
  <settings>
    <httpWebRequest useUnsafeHeaderParsing="true" />
  </settings>
</system.net>
```

**Comment by lontivero** [comment]
I've found many people reporting problem with upnp devices that response with malformed messages. Here an example: 
http://www.help-doing.com/sm/httpclient-throws-previously-well-known-exception-quotthe-server-committed-a-protocol-violation.shtml

Sadly, there is no way to set the useUnsafeHeaderParsing switch just for Open.NAT HttpClient instances. This means that the host applications can turn it on when it is appropiated but the Open.NAT library should never change settings that could have side effects on the hoster application.

**Comment by eugeniomiro** [comment]
Hi @lontivero, I found your link to be broken right now, could you please point to a fixed one or to the actual sample? Thanks!

**Comment by lontivero** [comment]
https://social.msdn.microsoft.com/Forums/windowsdesktop/en-US/e277643f-34d6-4d83-a15b-75301457059b/httpclient-throws-previously-well-known-exception-quotthe-server-committed-a-protocol-violation?forum=winappswithcsharp
