### ISSUE TITLE
Try to reinterprete error code 402 InvalidArguments for buggy devices 

### ISSUE THREAD

**Issue by lontivero** [lontivero/Open.NAT#51]
>Forum:	article "Open.NAT - A NAT Traversal library for .NET and Mono"
>Subject:	3 bugs   (View)
>Sender:	gunnarD
>Date:	Thursday, August 11, 2016 9:53am

Also many routers return error **402 InvalidArguments** instead of the more specific error(s), so I had to check for **UpnpConstants.InvalidArguments in GetSpecificMappingAsync, GetAllMappingsAsync and DeletePortMapAsync** and handle it the same way as the specific error ( UpnpConstants.SpecifiedArrayIndexInvalid \ UpnpConstants.NoSuchEntryInArray).

**Comment by osexpert** [comment]
Mayby only allow 402 for GetAllMappingsAsync as end of enumeration. The other methods can simply be wrapped in a try\catch by external code, without loss of function.

**Comment by lontivero** [comment]
This problem was fixed on commit 4bad61969c728e66fadd027dc4382a3db1d0ff60
[Fix defect #24 - GetSpecificMappingAsync under DD-WRT returns errorcode 402.](https://github.com/lontivero/Open.NAT/commit/4bad61969c728e66fadd027dc4382a3db1d0ff60)
