### ISSUE TITLE
UPnP discovery enabled in my router(Fritz!Box 7360) but openra using Open.NAT throws exception

### ISSUE THREAD

**Issue by maxpa1n87** [lontivero/Open.NAT#58]
Open.NAT Information: 0 : Start Discovery
Open.NAT Information: 0 : Searching for: UpnpSearcher
Open.NAT Information: 0 : UPnP Response: Router advertised a 'urn:schemas-upnp-org:service:WANIPConnection:1' service!!!
Open.NAT Information: 0 : Found device at: http://192.168.178.1:49000/igddesc.xml
Open.NAT Information: 0 : 192.168.178.1:49000: Fetching service list
Open.NAT Information: 0 : Found device at: http://192.168.178.1:49000/igddesc.xml
Open.NAT Error: 0 : Unhandled exception when trying to decode a device's response. 
Open.NAT Error: 0 : Report the issue in https://github.com/lontivero/Open.Nat/issues
Open.NAT Error: 0 : Also copy and paste the following info:
Open.NAT Error: 0 : -- beging ---------------------------------
Open.NAT Error: 0 : The requested feature is not implemented.
Open.NAT Error: 0 : Data string:
Open.NAT Error: 0 : HTTP/1.1 200 OK
LOCATION: http://192.168.178.1:49000/igddesc.xml
SERVER: FRITZ!Box Fon WLAN 7360 UPnP/1.0 AVM FRITZ!Box Fon WLAN 7360 124.06.30
CACHE-CONTROL: max-age=1800
EXT:
ST: urn:schemas-upnp-org:service:WANIPConnection:1
USN: uuid:75802409-bccb-40e7-8e6a-5C497962507E::urn:schemas-upnp-org:service:WANIPConnection:1

Open.NAT Error: 0 : -- end ------------------------------------
Open.NAT Information: 0 : UPnP Response: Router advertised a 'urn:schemas-upnp-org:service:WANIPConnection:1' service!!!
Open.NAT Information: 0 : Found device at: http://192.168.178.1:49000/igddesc.xml
Open.NAT Information: 0 : UPnP Response: Router advertised a 'urn:schemas-upnp-org:service:WANIPConnection:1' service!!!
Open.NAT Information: 0 : Found device at: http://192.168.178.1:49000/igddesc.xml
Open.NAT Information: 0 : UPnP Response: Router advertised a 'urn:schemas-upnp-org:service:WANIPConnection:1' service!!!
Open.NAT Information: 0 : Found device at: http://192.168.178.1:49000/igddesc.xml
Open.NAT Information: 0 : Stop Discovery
Open.NAT Information: 0 : Device not found. Common reasons:
Open.NAT Information: 0 : 	* No device is present or,
Open.NAT Information: 0 : 	* Upnp is disabled in the router or
Open.NAT Information: 0 : 	* Antivirus software is filtering SSDP (discovery protocol).
System.AggregateException:  ---> Open.Nat.NatDeviceNotFoundException: Exception of type 'Open.Nat.NatDeviceNotFoundException' was thrown.
  at Open.Nat.NatDiscoverer+<DiscoverDeviceAsync>d__5.MoveNext () [0x00000] in <filename unknown>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x00000] in <filename unknown>:0 
  at System.Runtime.CompilerServices.TaskAwaiter`1[Open.Nat.NatDevice].GetResult () [0x00000] in <filename unknown>:0 
  at OpenRA.Network.UPnP+<DiscoverNatDevices>c__async0.MoveNext () [0x00000] in <filename unknown>:0 
  --- End of inner exception stack trace ---
  at System.Threading.Tasks.Task.Wait (Int32 millisecondsTimeout, CancellationToken cancellationToken) [0x00000] in <filename unknown>:0 
  at System.Threading.Tasks.Task.Wait () [0x00000] in <filename unknown>:0 
  at OpenRA.Game.InitializeMod (System.String mod, OpenRA.Arguments args) [0x00000] in <filename unknown>:0 
 --> (Inner exception 0) Open.Nat.NatDeviceNotFoundException: Exception of type 'Open.Nat.NatDeviceNotFoundException' was thrown.
  at Open.Nat.NatDiscoverer+<DiscoverDeviceAsync>d__5.MoveNext () [0x00000] in <filename unknown>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x00000] in <filename unknown>:0 
  at System.Runtime.CompilerServices.TaskAwaiter`1[Open.Nat.NatDevice].GetResult () [0x00000] in <filename unknown>:0 
  at OpenRA.Network.UPnP+<DiscoverNatDevices>c__async0.MoveNext () [0x00000] in <filename unknown>:0

**Comment by lontivero** [comment]
It couldn't find a router in time. Is this a one-time error or does it fail always?

**Comment by maxpa1n87** [comment]
Every time I try to run openra and using the multiplayer function of the game I think. openra tells me that my router does not support UPNP but it surelly does. See the specs https://avm.de/produkte/fritzbox/fritzbox-7360/technische-daten/ (German language, maybe google will translate it for you :) )

**Comment by maxpa1n87** [comment]
You are welcome. I will do my best to help you.

**Comment by maxpa1n87** [comment]
Hi lontivero. It seems that it is a problem using mono 3.5.x. I just upgrade to mono 4.6.1. Now the nat.log seems to print that everything is correct.

`Open.NAT Information: 0 : Start Discovery
Open.NAT Information: 0 : Searching for: UpnpSearcher
Open.NAT Information: 0 : UPnP Response: Router advertised a 'urn:schemas-upnp-org:service:WANIPConnection:1' service!!!
Open.NAT Information: 0 : Found device at: http://192.168.178.1:49000/igddesc.xml
Open.NAT Information: 0 : 192.168.178.1:49000: Fetching service list
Open.NAT Information: 0 : Found device at: http://192.168.178.1:49000/igddesc.xml
Open.NAT Information: 0 : 192.168.178.1:49000: Parsed services list
Open.NAT Information: 0 : 192.168.178.1:49000: Found service: urn:schemas-upnp-org:service:WANIPConnection:1
Open.NAT Information: 0 : 192.168.178.1:49000: Found upnp service at: /igdupnp/control/WANIPConn1
Open.NAT Information: 0 : 192.168.178.1:49000: Handshake Complete
Open.NAT Information: 0 : Stop Discovery
Open.NAT Information: 0 : GetExternalIPAsync - Getting external IP address
Open.NAT Verbose: 0 : SOAPACTION: **GetExternalIPAddress** url:http://192.168.178.1:49000/igdupnp/control/WANIPConn1`

Can be closed from my side.

**Comment by lontivero** [comment]
Excellent. Thank you!
