### ISSUE TITLE
Incorrect default parameter on constructor

### ISSUE THREAD

**Issue by sheindel** [lontivero/Open.NAT#62]
This constructor claims to create a permanent mapping but it passes `int.MaxValue` which creates a 10 minute mapping. Needs to be changed to `0` be consistent with summary as well as other default constructor values. Mapping.cs, line 189-190

[https://github.com/lontivero/Open.NAT/blob/master/Open.Nat/Mapping.cs#L190](url)

```
public Mapping(Protocol protocol, int privatePort, int publicPort, string description)
	: this(protocol, IPAddress.None, privatePort, publicPort, int.MaxValue, description)
```

Should be

```
public Mapping(Protocol protocol, int privatePort, int publicPort, string description)
	: this(protocol, IPAddress.None, privatePort, publicPort, 0, description)
```

**Comment by lontivero** [comment]
Fixed in 6d54c86767578647f41ebea36c265ad6c7a7b107
