### ISSUE TITLE
Using it in Unity

### ISSUE THREAD

**Issue by Soahr** [lontivero/Open.NAT#67]
Don't understand how to use it with Unity.
Tasks doesn't exist in .net 3.5 so ?

**Comment by lontivero** [comment]
Open.NAT compiles and works okay with .NET 3.5. You can clone the repo, select a configuration for 3.5, build it and run it. It has a reference for the TaskParallelLibrary package that provides the Task class.

**Comment by Soahr** [comment]
Oh ok, thank you, just tried to use it as DLL before ...
Thank you very much, nice work !
